### ISSUE TITLE
rqt_rviz needs a build dependency on qtbase5-dev

### ISSUE THREAD

**Issue by tfoote** [ros-visualization/rqt_robot_plugins#102]
Like rviz [here](https://github.com/ros-visualization/rviz/blob/kinetic-devel/package.xml#L30)
This is the package with the cmake config files: https://packages.debian.org/jessie/amd64/qtbase5-dev/filelist

I think on ubuntu targets it's getting pulled in by an indirect dependency but on debian jessie it's not. 
Jessie package not installed: http://build.ros.org:8080/view/Kbin_dJ64/job/Kbin_dJ64__rqt_rviz__debian_jessie_amd64__binary/8/consoleFull
Xenial: http://build.ros.org:8080/view/Kbin_uX64/job/Kbin_uX64__rqt_rviz__ubuntu_xenial_amd64__binary/lastSuccessfulBuild/consoleFull It's brought in indirectly by rqt-gui

Rviz installed explicitly: http://build.ros.org:8080/view/Kbin_dJ64/job/Kbin_dJ64__rviz__debian_jessie_amd64__binary/10/consoleFull and works on debian.

**Comment by dirk-thomas** [comment]
The rosdep rule has already been updated: https://github.com/ros/rosdistro/commit/29a8e801294a64381f9ce43128657482df8ca923

It just needed a debinc released of `python_qt_binding` which already run-depends on this (https://github.com/ros-visualization/python_qt_binding/blob/621fc06a28370189537b8cc88eb03c7434be61e3/package.xml#L31): https://github.com/ros/rosdistro/pull/11384
