### ISSUE TITLE
rqt_robot_monitor: Stale Diagnostics Not Shown in Error Pane

### ISSUE THREAD

**Issue by DLu** [ros-visualization/rqt_robot_plugins#118]
The [package description](https://github.com/ros-visualization/rqt_robot_plugins/blob/master/rqt_robot_monitor/package.xml#L9) mentions that stale or error diagnostics are grouped together. However, the current implementation [only looks for error or warn](https://github.com/ros-visualization/rqt_robot_plugins/blob/master/rqt_robot_monitor/src/rqt_robot_monitor/robot_monitor.py#L143)

This is easy enough to fix, but I wanted to discuss whether other people thought it was a bug first.

**Comment by dirk-thomas** [comment]
This issue was moved to ros-visualization/rqt_robot_monitor#3
