### ISSUE TITLE
rqt_moveit: Begin topic monitoring automatically 

### ISSUE THREAD

**Issue by 130s** [ros-visualization/rqt_robot_plugins#17]
Right now user has to manually choose topics to start monitoring, and start it by right-clicking and choosing `Toggle monitoring`. It would be nice if this is automated.

This might involve changing `rqt_topic`, which is internally used in `rqt_moveit`.

**Comment by dirk-thomas** [comment]
This issue was moved to ros-visualization/rqt_moveit#1
