### ISSUE TITLE
rqt_moveit: Required topics unavailable errors should show in GUI

### ISSUE THREAD

**Issue by ablasdel** [ros-visualization/rqt_robot_plugins#76]
GUI should robustly handle common error cases

Currently if topic requirements are not met the console is repeatedly spammed as follows:
`
cannot ping [/move_group]: unknown node
[ERROR] [WallTime: 1416589782.318666] None of the following required topics are found.
(NAME, TYPE): [('/pointcloud', 'sensor_msgs/PointCloud'), ('/pointcloud2', 'sensor_msgs/PointCloud2'), ('/image', 'sensor_msgs/Image'), ('/camera_info', 'sensor_msgs/CameraInfo')]
[ERROR] [WallTime: 1416589783.318618] None of the following required topics are found.
(NAME, TYPE): [('/pointcloud', 'sensor_msgs/PointCloud'), ('/pointcloud2', 'sensor_msgs/PointCloud2'), ('/image', 'sensor_msgs/Image'), ('/camera_info', 'sensor_msgs/CameraInfo')]
[ERROR] [WallTime: 1416589784.318618] None of the following required topics are found.
(NAME, TYPE): [('/pointcloud', 'sensor_msgs/PointCloud'), ('/pointcloud2', 'sensor_msgs/PointCloud2'), ('/image', 'sensor_msgs/Image'), ('/camera_info', 'sensor_msgs/CameraInfo')]
[ERROR] [WallTime: 1416589785.318577] None of the following required topics are found.
(NAME, TYPE): [('/pointcloud', 'sensor_msgs/PointCloud'), ('/pointcloud2', 'sensor_msgs/PointCloud2'), ('/image', 'sensor_msgs/Image'), ('/camera_info', 'sensor_msgs/CameraInfo')]
[ERROR] [WallTime: 1416589786.318605] None of the following required topics are found.
(NAME, TYPE): [('/pointcloud', 'sensor_msgs/PointCloud'), ('/pointcloud2', 'sensor_msgs/PointCloud2'), ('/image', 'sensor_msgs/Image'), ('/camera_info', 'sensor_msgs/CameraInfo')]
`

**Comment by dirk-thomas** [comment]
Should be fixed by #119.
