### ISSUE TITLE
rqt_robot_monitor: Apparent threading bug

### ISSUE THREAD

**Issue by abencz** [ros-visualization/rqt_robot_plugins#78]
While running rqt_robot_monitor I get a continuous stream of the following in the parent terminal:

```
Traceback (most recent call last):
  File "/home/alex/ros_rocksteady_gui/src/rqt_robot_plugins/rqt_robot_monitor/src/rqt_robot_monitor/timeline_view.py", line 194, in _slot_redraw
    for i, m in enumerate(self._timeline):
  File "/home/alex/ros_rocksteady_gui/src/rqt_robot_plugins/rqt_robot_monitor/src/rqt_robot_monitor/timeline.p  y", line 158, in __iter__
    for msg in self._queue:
RuntimeError: deque mutated during iteration
```

Looks like the timeline queue is being modified by the ROS message callback in the `Timeline` class while at the same time being iterated over by `TimelineView`. I'm not what a good fix is, but I'm guessing this is causing more than just annoying error messages because I also see frequent rqt_robot_monitor freezes and crashes - most often when using the inspector window.

**Comment by ablasdel** [comment]
@abencz any updates?

**Comment by abencz** [comment]
Didn't get a chance to look at this before Christmas vacation. Will be looking at it next week.

**Comment by ablasdel** [comment]
No problem was just doing a check on all issue status. Thanks for looking into it!

**Comment by dirk-thomas** [comment]
This issue was moved to ros-visualization/rqt_robot_monitor#1
