### ISSUE TITLE
rqt_robot_monitor: UTF8 Messages not displayed correctly

### ISSUE THREAD

**Issue by mitchellwills** [ros-visualization/rqt_robot_plugins#79]
The robot monitor plugin does not appear to support using UTF8 strings. As shown below trying to send a UTF8 degree symbol (C2 B0) results in the first byte of the UTF8 sequence being treated as a seperate character.

![rqt_robot_monitor-utf8](https://cloud.githubusercontent.com/assets/427009/5886191/298caadc-a35c-11e4-9544-34b86a6a5504.png)

**Comment by dirk-thomas** [comment]
Where is the message being published? How is it encoded?

**Comment by mitchellwills** [comment]
I am publishing a diagnostics message from libsensors_monitor. Not that the change that publishes the degree symbol is only is my personal fork (https://github.com/mitchellwills/linux_peripheral_interfaces/). It is being created in C++ using "\xC2\xB0". This should be a unicode degree symbol (http://www.utf8-chartable.de/). Using rostopic echo displays the raw diagnostics message correctly. The ROS message wiki page (http://wiki.ros.org/msg) also encourages using UTF8 for encoding unicode strings.

**Comment by dirk-thomas** [comment]
The Python code of this plugin does not perform any decoding as far as I can see:

* https://github.com/ros-visualization/rqt_robot_plugins/blob/hydro-devel/rqt_robot_monitor/src/rqt_robot_monitor/status_item.py#L67
* https://github.com/ros-visualization/rqt_robot_plugins/blob/hydro-devel/rqt_robot_monitor/src/rqt_robot_monitor/status_snapshot.py#L64

Please consider to provide a pull request adding decoding of the message fields.

**Comment by dirk-thomas** [comment]
This issue was moved to ros-visualization/rqt_robot_monitor#2
