### ISSUE TITLE
Sweep of maintaintership status & release

### ISSUE THREAD

**Issue by ablasdel** [ros-visualization/rqt_robot_plugins#82]
In the coming weeks I will be doing a sweep of plugin status in this repo. 
Some of the items that are not maintained I will be taking maintainership of.

- [x] Update maintainership 
- [x] [Mark repo as Developed](https://github.com/ros/rosdistro/blob/master/indigo/distribution.yaml#L7548)
- [ ] Release again to ensure bag plugin gets installed

**Comment by ablasdel** [comment]
PR created to mark as developed: https://github.com/ros/rosdistro/pull/8242

**Comment by dirk-thomas** [comment]
Released into Jade: ros/rosdistro#8261

**Comment by dirk-thomas** [comment]
Also released into Indigo and Hydro: http://www.ros.org/debbuild/compare_groovy_hydro_indigo_jade.html?q=rqt
