### ISSUE TITLE
rqt_rviz: rviz config file should be available for specifying when using inside of a perspective

### ISSUE THREAD

**Issue by awesomebytes** [ros-visualization/rqt_robot_plugins#86]
As this ROS answers question illustrates:
http://answers.ros.org/question/202558/how-to-load-rviz-with-a-specific-config-file-when-starting-rqt/

It would be very nice to be able to load a .rviz file when loading the rqt_rviz plugin.

Currently it loads whatever is in the ~/.rviz/default.rviz

**Comment by dirk-thomas** [comment]
This issue was moved to ros-visualization/rqt_rviz#1
