### ISSUE TITLE
Wiki Page Link Broken

### ISSUE THREAD

**Issue by DLu** [ros-visualization/rqt_robot_plugins#91]
On http://wiki.ros.org/rqt_robot_dashboard, the link to the Python docs (http://docs.ros.org/groovy/api/rqt_robot_dashboard/html/doc/) is broken.

**Comment by dirk-thomas** [comment]
Can you please update the wiki page with the correct link. It looks like it should point to http://docs.ros.org/api/rqt_robot_dashboard/html/ instead.

**Comment by dirk-thomas** [comment]
On the other the `Code API` link is already on the right side. Maybe removing the `Documentation` block all together makes more sense.

**Comment by DLu** [comment]
I knew the Code API link was there, but I was hoping there was a different link with more documentation.
